name: Build Cordova Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install Cordova CLI
      run: npm install -g cordova

    - name: Install dependencies and build project
      run: |
        npm install
        cordova platform add android
        cordova prepare
        cordova build android --release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: platforms/android/app/build/outputs/apk/release/app-release.apk
        
