name: Build Cordova Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Cordova CLI
      run: npm install -g cordova

    - name: Install dependencies and build project
      run: |
        npm install
        cordova platform add android
        cordova prepare
        cordova build android

    - name: List output files
      run: ls -R /platforms/
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: enchanti-ide.apk
        path: platforms/android/app/build/outputs/apk/release/enchanti-ide.apk
    
